#!/usr/bin/env sh

set -e

case "$1" in
chop|init|install|purge|remove|stow|test|unstow|unstow-curr)
        action="$1"
        shift 1
;;
*)
        echo "noop" 1>&2;
        exit 1
esac

expr=""

for _e in "$1" "${2:-_}"
do
        case "$_e" in
        local)
                readonly expr="-e |local"
        ;;
        global)
                expr="${expr} -e |global"
        ;;
        system)

                expr="${expr} -e |system"
        esac
done

: ${expr:? context missing}

cd -- "/home/latch/var/ring"

grep -F ${expr} "./LINFO" \
| sed -e 's#|.*$##' \
| {
        set +e
        while
                IFS= read -r n
        do
                ../../bin/latch pkg "$action" "$n"
        done
};

# vim: set ts=8 sw=8 tw=0 et :
