#!/bin/sh

set -e;

expr=;
action=$1;
shift 1;

for e in "$1" ${2:-_};
do
	case $e in
		(local)
			expr="-e |local";
			readonly expr;;
		(global)
			expr="$expr -e |global";;
		(system)
			expr="$expr -e |system";;
	esac;
done;

: "${expr:? context missing}";

set -f;
IFS=' ';

case $action in
	(build|chop|init|install|purge|remove)
		cd -- "/home/latch/var/ring";
		git grep \
			-F \
			--color=never \
			-h \
			$expr \
			master \
			-- ./LINFO 2>/dev/null |
		sed -e 's#|.*$##' | {
			set +e;
			while
				IFS= read -r n;
			do
				../../bin/latch pkg "$action" "$n";
			done;
		};
	;;
	(add|delete)
		cd -- "/home/latch/var";
		grep -F $expr ./pkg.list |
		sed -e 's#|.*$##' |
		sed -e 's|::|/|g' | {
			set +e;
			while
				IFS= read -r n;
			do
				../bin/latch stow "$action" "$n";
			done;
		};;
	(*)
		echo noop 1>&2;
		exit 1;
esac;

# vim: set ft=sh :
